---
abstract: 'Create init scripts for Perl high-available (HA) daemons'
author:
  - 'Ivan Kruglov, C<ivan.kruglov@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HADaemon-Control
no_index:
  directory:
    - inc
requires:
  Cwd: 0
  File::Path: '2.08'
  IPC::ConcurrencyLimit::WithStandby: 0
  POSIX: 0
  Scalar::Util: 0
  perl: 5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: '0.8'
